tr1:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      JointRightShoulderPan:
        type: effort_controllers/JointPositionController
        joint: JointRightShoulderPan
        pid: {p: 10.0, i: 0.0, d: 1.0}
      JointRightShoulderTilt:
        type: effort_controllers/JointPositionController
        joint: JointRightShoulderTilt
        pid: {p: 10.0, i: 0.0, d: 1.0}
      JointRightUpperArmRoll:
        type: effort_controllers/JointPositionController
        joint: JointRightUpperArmRoll
        pid: {p: 10.0, i: 0.0, d: 1.0}
      JointRightElbowFlex:
        type: effort_controllers/JointPositionController
        joint: JointRightElbowFlex
        pid: {p: 10.0, i: 0.0, d: 1.0}
      JointRightForearmRoll:
        type: effort_controllers/JointPositionController
        joint: JointRightForearmRoll
        pid: {p: 10.0, i: 0.0, d: 1.0}
      JointRightWristFlex:
        type: effort_controllers/JointPositionController
        joint: JointRightWristFlex
        pid: {p: 10.0, i: 0.0, d: 1.0}
    effort:
      JointRightShoulderPan:
        type: effort_controllers/JointEffortController
        joint: JointRightShoulderPan
      JointRightShoulderTilt:
        type: effort_controllers/JointEffortController
        joint: JointRightShoulderTilt
      JointRightUpperArmRoll:
        type: effort_controllers/JointEffortController
        joint: JointRightUpperArmRoll
      JointRightElbowFlex:
        type: effort_controllers/JointEffortController
        joint: JointRightElbowFlex
      JointRightForearmRoll:
        type: effort_controllers/JointEffortController
        joint: JointRightForearmRoll
      JointRightWristFlex:
        type: effort_controllers/JointEffortController
        joint: JointRightWristFlex
      JointRightWristRoll:
        type: effort_controllers/JointEffortController
        joint: JointRightWristRoll
      JointRightGripper:
        type: effort_controllers/JointEffortController
        joint: JointRightGripper
