tr1:
  hardware_interface:
     loop_hz: 10 # hz
     joints:
       - JointRightShoulderPan
       - JointRightShoulderTilt
       - JointRightUpperArmRoll
       - JointRightElbowFlex
       - JointRightForearmRoll
       - JointRightWristFlex
       - JointRightWristRoll
       - JointRightGripper
