tr1:
  joint_offsets:
    JointLeftElbowFlex: -0.0
    JointLeftForearmRoll: -0.0
    JointLeftGripper: -0.0
    JointLeftShoulderPan: -0.0
    JointLeftShoulderTilt: -0.0
    JointLeftUpperArmRoll: -0.0
    JointLeftWristFlex: -0.0
    JointLeftWristRoll: -0.0
    JointRightElbowFlex: -0.17180584824320314
    JointRightForearmRoll: -6.332272692392344
    JointRightGripper: -0.0
    JointRightShoulderPan: -1.8898643306752345
    JointRightShoulderTilt: -0.9940195505499609
    JointRightUpperArmRoll: -1.5155730184311134
    JointRightWristFlex: 0.049087385212343904
    JointRightWristRoll: -0.0
    base_to_body: -0.0
    base_to_wheel1: -0.0
    base_to_wheel2: -0.0
    base_to_wheel3: -0.0
    base_to_wheel4: -0.0
    neck_base_to_neck: -0.0
    neck_to_head: -0.0
  joint_read_ratio:
    JointLeftElbowFlex: 0.0
    JointLeftForearmRoll: 0.0
    JointLeftGripper: 0.0
    JointLeftShoulderPan: 0.0
    JointLeftShoulderTilt: 0.0
    JointLeftUpperArmRoll: 0.0
    JointLeftWristFlex: 0.0
    JointLeftWristRoll: 0.0
    JointRightElbowFlex: 0.944444444
    JointRightForearmRoll: 1.076923077
    JointRightGripper: 1.0
    JointRightShoulderPan: 1.0
    JointRightShoulderTilt: 1.0
    JointRightUpperArmRoll: 1.076923077
    JointRightWristFlex: 0.923076923
    JointRightWristRoll: 1.0
